site_name: Observability関連Note
theme:
  name: material
  lang: 'ja'
  palette:
    - scheme: slate
      primary: teal
      accent: purple
      toggle:
        icon: material/toggle-switch-off-outline
        name: Swich to Light mode    
    - scheme: default
      toggle:
        icon: material/toggle-switch
        name: Switch to Dark mode
      primary: teal
      accent: lime
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
nav:
  - はじめに: index.md
  - turbonomic:
    - prome-turbo: prome-turbo.md
    - prometheus: prometheus.md
  - Instana:
    - Instana概要: instana.md
  - その他メモ:
    - Prometheusについて: prometheus.md
extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/
    - icon: fontawesome/brands/twitter
      link: https://twitter.com
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/

markdown_extensions:
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - admonition
  - pymdownx.superfences
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
copyright: |
  &copy; 2023 <a href="https://github.com/junkisagawa"  target="_blank" rel="noopener">Junki Sagawa</a>
