site_name: コンテナ・ハンズオン (仮)
theme:
  name: material
  lang: 'ja'
  font:
    text: IBM Plex Sans JP Light
    code: Inconsolata
  palette:
    - scheme: slate
      primary: teal
      accent: purple
      toggle:
        icon: material/toggle-switch-off-outline
        name: Swich to Light mode    
    - scheme: default
      toggle:
        icon: material/toggle-switch
        name: Switch to Dark mode
      primary: teal
      accent: purple
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
nav:
  - はじめに: index.md
  - コンテナ編:
    - 準備: 100-prerequired.md
    - コンテナファイルの基本記述: 101-container_file.md
    - コンテナイメージのビルド: 103-container-build.md
    - 複数のコンテナを連携させよう: 104-Integration-ap_and_db.md
    - コンテナリポジトリーへのpush: 105-container_image_registry.md
  - コンテナオーケストレーション編:
    - OpenShift Localの起動: 201-opening.md
  - 参考情報: 
    - Podmanの基本: option1-podman.md
    - 12Factors - Cloud Native Architectureの基本: option2-12factors.md
extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/
    - icon: fontawesome/brands/twitter
      link: https://twitter.com
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/
extra_css:
  - stylesheets/extra.css
markdown_extensions:
  - codehilite:
      linenums: true
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - admonition
  - pymdownx.superfences
  - footnotes
  - pymdownx.details
  - pymdownx.mark
  - attr_list
  - md_in_html
copyright: |
  &copy; 2023 <a href="https://github.com/junkisagawa"  target="_blank" rel="noopener">Junki Sagawa</a>
